[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = 'DeinUpdate'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = { 'n' = '<Plug>' }

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = ['BufReadPre', 'BufNewFile']
hook_source = '''
augroup user_plugin_cursorword
  autocmd!
  autocmd FileType defx,denite,fern,clap,vista let b:cursorword = 0
  autocmd WinEnter * if &diff || &pvw | let b:cursorword = 0 | endif
  autocmd InsertEnter * let b:cursorword = 0
  autocmd InsertLeave * let b:cursorword = 1
augroup END
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Glog', 'Gdiff', 'Gstatus', 'Git!', 'Grebase', 'Gpull']

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'justinmk/vim-sneak'
depends = ['vim-repeat']
hook_source = '''
let g:sneak#label = 1
let g:sneak#s_next = 1
'''

[[plugins]]
repo = 'junegunn/vim-slash'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = ['FloatermNew', 'FloatermToggle', 'FloatermPrev', 'FloatermNext', 'FloatermSend', 'FloatermKill']
hook_source = '''
let g:floaterm_wintype = 'floating'
let g:floaterm_position = 'center'
let g:floaterm_autoinsert = v:true
let g:floaterm_title = 'terminal [$1/$2]'
'''

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'MundoToggle'
on_source = '''
set undofile
set undodir=$HOME/.vim/.cache/undo
let g:mundo_width = 50
let g:mundo_preview_height = 30
let g:mundo_right = 1
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_source = '''
let g:asyncrun_open = 25
let g:asyncrun_bell = 1
let g:asyncrun_rootmarks = ['.svn', '.git', '.root', '_darcs', 'build.xml']
'''

[[plugins]]
repo = 'skywind3000/asynctasks.vim'
depends = 'asyncrun.vim'
hook_source = '''
let g:asynctasks_term_pos = 'right'
let g:asynctasks_term_reuse = 0
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = ['Vista', 'Vista!', 'Vista!!']
hook_source = '''
let g:vista#renderer#enable_icon = 1
let g:vista_default_executive = 'ctags'
let g:vista_echo_cursor = 0
let g:vista_fzf_preview = ['right:50%']
let g:vista_executive_for = {
  \ 'c': 'coc',
  \ 'go': 'coc',
  \ 'cpp': 'coc',
  \ 'php': 'coc',
  \ 'javascript': 'coc',
  \ 'typescript': 'coc',
  \ 'vimwiki': 'markdown',
  \ 'pandoc': 'markdown',
  \ 'markdown': 'toc',
  \ }
'''

[[plugins]]
repo = 'liuchengxu/vim-clap'
merged = 0
build = 'bash install.sh'
on_map = '<plug>'
hook_source = '''
let g:clap_default_external_filter = 'fzy'
let g:clap_cache_directory = $DATA_PATH . '/clap'
let g:clap_layout = { 'relative': 'editor' }
let g:clap_enable_icon = 1
" let g:clap_popup_border = 'sharp'
let g:clap_provider_grep_enable_icon = 1
let g:clap_insert_mode_only = v:true
" let g:clap_search_box_border_style = 'curve'
let g:clap_current_selection_sign= { 'text': "\uf124", 'texthl': "ClapCurrentSelectionSign", "linehl": "ClapCurrentSelection"}
'''

[[plugins]]
repo = 'vn-ki/coc-clap'
on_source = 'vim-clap'

[[plugins]]
repo = 'brooth/far.vim'
on_cmd = ['Far', 'Fardo', 'Farundo', 'F', 'Farr']
hook_source = '''
let g:far#enable_undo=1
" let g:far#source = 'rg'
'''

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = { 'x' = '<Plug>' }

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tyru/caw.vim'
depends = ['vim-operator-user']
on_map = { 'nx' = '<Plug>' }
hook_source = '''
let g:caw_operator_keymappings = 0
'''

[[plugins]]
repo = 'matze/vim-move'
hook_source = '''
let g:move_key_modifier = 'C'
'''
