[[plugins]]
repo = 'Shougo/dein.vim'
on_func = 'dein#'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Glog', 'Gdiff', 'Gstatus', 'Git!', 'Grebase', 'Gpull']

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'justinmk/vim-sneak'
hook_source = '''
let g:sneak#label = 1
let g:sneak#target_labels = ";sftunq/SFGHLTUNRMQZ?0"
'''

[[plugins]]
repo = 'junegunn/vim-slash'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = ['FloatermNew', 'FloatermToggle', 'FloatermPrev', 'FloatermNext', 'FloatermSend']
hook_source = '''
let g:floaterm_wintype = 'normal'
let g:floaterm_position = 'bottom'
let g:floaterm_height = 0.35
let g:floaterm_keymap_toggle = '<Ctrl>-d'
let g:floaterm_open_command = 'split'
highlight Floaterm guibg=black
'''

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'MundoToggle'
on_source = '''
set undofile
set undodir=$HOME/.vim/.cache/undo
let g:mundo_width = 50
let g:mundo_preview_height = 30
let g:mundo_right = 1
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_source = '''
let g:asyncrun_open = 25
let g:asyncrun_bell = 1
let g:asyncrun_rootmarks = ['.svn', '.git', '.root', '_darcs', 'build.xml']
'''

[[plugins]]
repo = 'skywind3000/asynctasks.vim'
depends = 'asyncrun.vim'
hook_source = '''
let g:asynctasks_term_pos = 'right'
let g:asynctasks_term_reuse = 0
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = ['Vista', 'Vista!', 'Vista!!']
hook_source = '''
let g:vista#renderer#enable_icon = 1
let g:vista_default_executive = 'ctags'
let g:vista_echo_cursor = 0
let g:vista_fzf_preview = ['right:50%']
let g:vista_executive_for = {
  \ 'c': 'coc',
  \ 'go': 'coc',
  \ 'cpp': 'coc',
  \ 'php': 'coc',
  \ 'javascript': 'coc',
  \ 'typescript': 'coc',
  \ 'vimwiki': 'markdown',
  \ 'pandoc': 'markdown',
  \ 'markdown': 'toc',
  \ }
'''

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_source = '''
let g:NERDSpaceDelims = 1
let g:NERDCreateDefaultMappings = 0
let g:NERDRemoveExtraSpaces = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
'''

[[plugins]]
repo = 'liuchengxu/vim-clap'
merged = 0
build = 'bash install.sh'
on_map = '<plug>'
hook_source = '''
let g:clap_cache_directory = $DATA_PATH . '/clap'
let g:clap_layout = { 'relative': 'editor' }
let g:clap_enable_icon = 1
let g:clap_popup_border = 'sharp'
let g:clap_provider_grep_enable_icon = 1
let g:clap_insert_mode_only = v:true
" let g:clap_search_box_border_style = 'curve'
let g:clap_current_selection_sign= { 'text': "\uf124", 'texthl': "ClapCurrentSelectionSign", "linehl": "ClapCurrentSelection"}
'''

[[plugins]]
repo = 'vn-ki/coc-clap'
on_source = 'vim-clap'

[[plugins]]
repo = 'Yggdroot/indentLine'
on_event = 'BufReadPost'
hook_source = '''
let g:indentLine_char = 'â”Š'
let g:indentLine_fileType = ['python', 'vim', 'json']
let g:indentLine_concealcursor = 'niv'
let g:indentLine_conceallevel = 2
'''
