[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_source = 'lua require("lb.config.theme")'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_source = 'lua require("lb.config.vim-startify")'

# [[plugins]]
# repo = 'mengelbrecht/lightline-bufferline'
# 
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_source = 'lua require("lb.config.lightline").on_attach()'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
hook_source = 'lua require("lb.config.eviline")'

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
hook_source = "lua require('lb.config.nvim-tree').on_attach()"
