# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# ui
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
if !empty($TMUX) 
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  if has('termguicolors')
    set t_8f=^[[38;2;%lu;%lu;%lum
    set t_8b=^[[48;2;%lu;%lu;%lum
    set termguicolors
  else
    set t_Co=256
  endif
  if &ttimeoutlen > 60 || &ttimeoutlen <= 0
    set ttimeoutlen=60
  endif
endif
" 退出后清屏
if &term =~ "xterm"
  let &t_ti = "\<Esc>[?47h"
  let &t_te = "\<Esc>[?47l"
endif
set background=dark
set number
set fillchars+=vert:\|  " add a bar for vertical splits
set fcs=eob:\           " hide ~
set nolist

let g:gruvbox_filetype_hi_groups = 1
let g:gruvbox_plugin_hi_groups = 1
let g:gruvbox_transp_bg = 1
let g:gruvbox_material_background = 'soft'
colorscheme gruvbox-material

hi Whitespace ctermfg=96 guifg=#725972 guibg=NONE ctermbg=NONE
" hi PMenuSel ctermfg=252 ctermbg=106 guifg=#d0d0d0 guibg=#859900 guisp=#859900 cterm=NONE gui=NONE
'''

[[plugins]]
repo = 'mhinz/vim-startify'
depends = ['vim-devicons']
hook_add = 'source $MD/startify.vim'
hook_post_source = '''
highlight StartifyHeader guifg=#FF00FF
highlight StartifyNumber guifg=#00FF00
highlight StartifyPath   guifg=#00AFFF
highlight StartifySlash  guifg=#DF875F
function! StartifyEntryFormat()
  return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
endfunction
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-devicons']
hook_add = 'source $MD/lightline.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
depends = ['lightline.vim']


[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source = '''
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'machakann/vim-sandwich'
depends = ['vim-textobj-user']

[[plugins]]
repo = 'dominikduda/vim_current_word'
hook_add = '''
let g:vim_current_word#enabled = 1
let g:vim_current_word#highlight_delay = 0
let g:vim_current_word#highlight_twins = 1
let g:vim_current_word#highlight_current_word = 1
let g:vim_current_word#highlight_only_in_focused_window = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'v0.0.77'
hook_source = 'source $MD/coc.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'skywind3000/vim-quickui'
on_func = 'quickui#'
hook_source = 'source $MD/quickui.vim'

[[plugins]]
repo = 'StanAngeloff/php.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'neoclide/jsonc.vim'
on_ft = ['json', 'jsonc']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

